### ISSUE TITLE
A DECENTRALIZED VOTING APP USING BLOCKCHAIN - Presentation Document

### ISSUE THREAD

**Issue by zbuseze** [CankayaUniversity/ceng-407-408-2021-2022-A-Decentralized-Voting-App-using-Blockchain#9]
Presentation pages titled Main Problems, E-Voting Analysis, Problems and Solution of Developing Online Voting System were created. You can add what you will talk about in the presentation.

**Comment by akkayalperen** [comment]
Completed.
